config/routes.rb
Rails.application.routes.draw do
  resources :garden_layouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   post 'authenticate', to: 'authentication#authenticate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden_layout.rb
class GardenLayout < ApplicationRecord
  belongs_to :user  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :garden_layouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_request
  attr_reader :current_user

  private

  def authenticate_request
   @current_user = AuthorizeApiRequest.call(request.headers).result
   render json: { error: 'Not Authorized' }, status: 401 unless @current_user
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  skip_before_action :authenticate_request

  def authenticate
    command = AuthenticateUser.call(params[:email], params[:password])
    if command.success?
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end
end

app/controllers/garden_layouts_controller.rb
class GardenLayoutsController < ApplicationController
  before_action :set_garden_layout, only: [:show, :edit, :update, :destroy]

  # GET /garden_layouts
  # GET /garden_layouts.json
  def index
    render json: current_user.garden_layouts.to_json
  end

  # GET /garden_layouts/1
  # GET /garden_layouts/1.json
  def show
  end

  # GET /garden_layouts/new
  def new
    @garden_layout = GardenLayout.new
  end

  # GET /garden_layouts/1/edit
  def edit
  end

  # POST /garden_layouts
  # POST /garden_layouts.json
  def create
    @garden_layout = GardenLayout.new(garden_layout_params)

    respond_to do |format|
      if @garden_layout.save
        format.html { redirect_to @garden_layout, notice: 'Garden layout was successfully created.' }
        format.json { render :show, status: :created, location: @garden_layout }
      else
        format.html { render :new }
        format.json { render json: @garden_layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /garden_layouts/1
  # PATCH/PUT /garden_layouts/1.json
  def update
    respond_to do |format|
      if @garden_layout.update(garden_layout_params)
        format.html { redirect_to @garden_layout, notice: 'Garden layout was successfully updated.' }
        format.json { render :show, status: :ok, location: @garden_layout }
      else
        format.html { render :edit }
        format.json { render json: @garden_layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garden_layouts/1
  # DELETE /garden_layouts/1.json
  def destroy
    @garden_layout.destroy
    respond_to do |format|
      format.html { redirect_to garden_layouts_url, notice: 'Garden layout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden_layout
      @garden_layout = GardenLayout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def garden_layout_params
      params.require(:garden_layout).permit(:id, :data, :compeleted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garden_layouts_helper.rb
module GardenLayoutsHelper
end

app/views/garden_layouts/_form.html.erb
<%= form_for(garden_layout) do |f| %>
  <% if garden_layout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garden_layout.errors.count, "error") %> prohibited this garden_layout from being saved:</h2>

      <ul>
      <% garden_layout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %>
    <%= f.text_field :id %>
  </div>

  <div class="field">
    <%= f.label :data %>
    <%= f.text_field :data %>
  </div>

  <div class="field">
    <%= f.label :compeleted %>
    <%= f.check_box :compeleted %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/garden_layouts/edit.html.erb
<h1>Editing Garden Layout</h1>

<%= render 'form', garden_layout: @garden_layout %>

<%= link_to 'Show', @garden_layout %> |
<%= link_to 'Back', garden_layouts_path %>

app/views/garden_layouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Garden Layouts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Data</th>
      <th>Compeleted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @garden_layouts.each do |garden_layout| %>
      <tr>
        <td><%= garden_layout.id %></td>
        <td><%= garden_layout.data %></td>
        <td><%= garden_layout.compeleted %></td>
        <td><%= link_to 'Show', garden_layout %></td>
        <td><%= link_to 'Edit', edit_garden_layout_path(garden_layout) %></td>
        <td><%= link_to 'Destroy', garden_layout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden Layout', new_garden_layout_path %>

app/views/garden_layouts/new.html.erb
<h1>New Garden Layout</h1>

<%= render 'form', garden_layout: @garden_layout %>

<%= link_to 'Back', garden_layouts_path %>

app/views/garden_layouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @garden_layout.id %>
</p>

<p>
  <strong>Data:</strong>
  <%= @garden_layout.data %>
</p>

<p>
  <strong>Compeleted:</strong>
  <%= @garden_layout.compeleted %>
</p>

<%= link_to 'Edit', edit_garden_layout_path(@garden_layout) %> |
<%= link_to 'Back', garden_layouts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GradenPlanningAppApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>